pipeline:
  log_path: pipeline_logs.log'
  experiment_name: 'Credit-Card-Fraud-Detection'
  run_name: 'pipeline'
  version: '1.0.0'
  pipeline_status: 'completed'

ingest:
  run_name: 'data_ingestion'
  schema_path : 'src/datapipeline/config/data_schema.yaml'
  input_path: 'data/raw/creditcard.csv'
  raw_dataset_path_parquet: 'data/raw/creditcard.parquet'
  raw_dataset_artifact_name: 'raw_dataset'
  raw_dataset_path_mlflow: 'raw_data'

data_cleaning:
  run_name: 'data_cleaning'
  cleaned_dataset_path: 'data/cleaned/creditcard_cleaned.parquet'
  target_column: 'Class'
  min_samples: 1000
  num_classes: 2
  cleaned_dataset_path_mlflow: cleaned_dataset

data_split:
  run_name: 'data_split'
  test_size: 0.3
  random_state: 42
  train_path: 'data/splits/train.parquet'
  test_path: 'data/splits/test.parquet'
  tolerance: 0.01
  train_artifact_path_mlflow: 'train' 
  test_artifact_path_mlflow: 'test'
  
diagnostics:
  run_name: 'correlation diagnostics'
  correlation_matrix: 'artifacts/eda/correlation/correlation_matrix.parquet'
  correlation_metadata: 'artifacts/eda/correlation/correlation_matedata.parquet'
  correlation_heatmap: 'artifacts/eda/correlation/correlation_heatmap.png'
  correlation_path_mlflow: 'correlation_diagnostics'

feature_engineering:
  run_name: 'feature engineering'
  remove_correlated_features: 1
  threshold_correlation: 0.95
  correlated_features_path : 'artifacts/feature_engineering/correlation/correlated_features.parquet'
  correlated_features_path_mlflow : 'correlated_features'
  train_path_feature_engineered: 'data/splits//feature_engineered/train_fe.parquet'
  test_path_feature_engineered: 'data/splits//feature_engineered/test_fe.parquet'
  train_path_feature_engineered_mlflow: 'train_feature_engineered'
  test_path_feature_engineered_mlflow: 'test_feature_engineered'

  
  
model_selection:
  artifacts_path: 'artifacts//model_selection'

model_tuning:
  artifacts_path: 'artifacts/model_tuning'

threshold_tuning:
  artifacts_path: 'artifacts/threshold_tuning'

model_training:
  run_name: 'Model_Training'
  random_state: 42
  model_name: 'CatBoost'
  l2_leaf_reg: 2.53
  depth: 8
  iterations: 789
  learning_rate: 0.02
  threshold: 0.28
  classification_threshold_file_name: "classification_threshold.json"
  artifacts_path_mlflow_model_training: "model_config"
  registered_model_name: "fraud_catboost"
  artifacts_path_model_training: 'artifacts/model_training'

inference: 
  run_name: 'inference'
  artifacts_path_inference: 'artifacts/inference/predictions.parquet'
  artifacts_path_inference_mlflow: 'inference'