pipeline:
  log_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/logs/pipeline_logs.log'
  experiment_name: 'Credit-Card-Fraud-Detection'


data_ingestion:
  dataset_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/raw/creditcard.csv'
  schema_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/src/datapipeline/config/data_schema.yaml'

data:
  target_column: 'Class'
  min_samples: 1000
  num_classes: 2
  tolerance: 0.01
  
data_split:
  test_size: 0.3
  random_state: 42
  train_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/splits/train.parquet'
  test_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/splits/test.parquet'
  
diagnostics:
  correlation_matrix: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/eda/correlation/correlation_matrix.parquet'
  correlation_metadata: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/eda/correlation/correlation_matedata.parquet'
  correlation_heatmap: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/eda/correlation/correlation_heatmap.png'

feature_engineering:
  remove_correlated_features: 1
  threshold: 0.95
  correlated_features : '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/feature_engineering/correlation/correlated_features.parquet'
  train_path_feature_engineered: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/splits//feature_engineered/train_fe.parquet'
  test_path_feature_engineered: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/splits//feature_engineered/test_fe.parquet'
  
model_selection:
  artifacts_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts//model_selection'

model_tuning:
  artifacts_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/model_tuning'

threshold_tuning:
  artifacts_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/artifacts/threshold_tuning'

model_training:
  random_state: 42
  model_name: 'CatBoost'
  l2_leaf_reg: 2.53
  depth: 8
  iterations: 789
  learning_rate: 0.02
  threshold: 0.28
